Combining Array


In [1]:
import numpy as np

In [2]:
arr=np.arange(20)

In [3]:
arr.dtype

dtype('int32')

In [14]:
np.size(arr)

20

In [17]:
arr1=arr.reshape(4,5)

In [18]:
arr1.dtype

dtype('int32')

In [19]:
np.size(arr1)

20

In [21]:
arr2=np.arange(25).reshape(5,5)

HOW TO COMBINE BOTH ARRAY TO EACH OTHER
COLUMN WISE COMBINE MEANS HORIZENTAL STACKING
ROW WISE COMBINE MEANS VERTICAL STACKING

In [22]:
np.vstack((arr1,arr2))  #row wise combination, if we want to combine row wise its means rows of both arrays are equal to each other

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
np.hstack((arr1,arr2))  #column wise stacking,Error indicate that column_arr1!= column_arr2 its must be equal to each other for combination


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 5

In [55]:
arr3=np.concatenate((arr1,arr2) , 1)#concatenate Function Basically use for joining two or more arrays but difference size
arr3

array([[ 0,  1,  2,  3,  0,  1,  2,  3,  4],
       [ 4,  5,  6,  7,  5,  6,  7,  8,  9],
       [ 8,  9, 10, 11, 10, 11, 12, 13, 14],
       [12, 13, 14, 15, 15, 16, 17, 18, 19],
       [16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [29]:
np.shape(arr3)

(9, 5)

In [30]:
arr4=np.arange(25).reshape(5,5)

In [31]:
arr5=np.arange(30).reshape(5,6)

In [32]:
np.hstack((arr4,arr5))

array([[ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4,  5],
       [ 5,  6,  7,  8,  9,  6,  7,  8,  9, 10, 11],
       [10, 11, 12, 13, 14, 12, 13, 14, 15, 16, 17],
       [15, 16, 17, 18, 19, 18, 19, 20, 21, 22, 23],
       [20, 21, 22, 23, 24, 24, 25, 26, 27, 28, 29]])

In [33]:
np.vstack((arr4 , arr5))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 5 and the array at index 1 has size 6

if rows are diferent but columns are same Its means column combination never exist
if column difference its means rows stacking its not exist

In [37]:
np.concatenate((arr4,arr5) , 1)  #0 showes the rows(y-axis), 1 shows the column(x-axis)

array([[ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4,  5],
       [ 5,  6,  7,  8,  9,  6,  7,  8,  9, 10, 11],
       [10, 11, 12, 13, 14, 12, 13, 14, 15, 16, 17],
       [15, 16, 17, 18, 19, 18, 19, 20, 21, 22, 23],
       [20, 21, 22, 23, 24, 24, 25, 26, 27, 28, 29]])

In [39]:
np.concatenate((arr4,arr5), 1)    # syntax  numpy.concatenate(arrys  , keys)

array([[ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4,  5],
       [ 5,  6,  7,  8,  9,  6,  7,  8,  9, 10, 11],
       [10, 11, 12, 13, 14, 12, 13, 14, 15, 16, 17],
       [15, 16, 17, 18, 19, 18, 19, 20, 21, 22, 23],
       [20, 21, 22, 23, 24, 24, 25, 26, 27, 28, 29]])

In [5]:
arr1=np.arange(20).reshape(5,4)
arr2=np.arange(25).reshape(5,5)
arr3=np.arange(30).reshape(5,6)
np.hstack((arr1 , arr2 , arr3))

array([[ 0,  1,  2,  3,  0,  1,  2,  3,  4,  0,  1,  2,  3,  4,  5],
       [ 4,  5,  6,  7,  5,  6,  7,  8,  9,  6,  7,  8,  9, 10, 11],
       [ 8,  9, 10, 11, 10, 11, 12, 13, 14, 12, 13, 14, 15, 16, 17],
       [12, 13, 14, 15, 15, 16, 17, 18, 19, 18, 19, 20, 21, 22, 23],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 24, 25, 26, 27, 28, 29]])

In [10]:

np.concatenate((arr1,arr2,arr3) , axis=0)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 5

In [66]:
arr1=np.arange(25).reshape(5,5)
arr2=np.arange(25).reshape(5,5)
np.dstack((arr1,arr2))

array([[[ 0,  0],
        [ 1,  1],
        [ 2,  2],
        [ 3,  3],
        [ 4,  4]],

       [[ 5,  5],
        [ 6,  6],
        [ 7,  7],
        [ 8,  8],
        [ 9,  9]],

       [[10, 10],
        [11, 11],
        [12, 12],
        [13, 13],
        [14, 14]],

       [[15, 15],
        [16, 16],
        [17, 17],
        [18, 18],
        [19, 19]],

       [[20, 20],
        [21, 21],
        [22, 22],
        [23, 23],
        [24, 24]]])

In [75]:
arr=np.arange(15,24).reshape(3,3)

In [76]:
np.max(arr)      

23

In [77]:
arr

array([[15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [78]:
np.min(arr)

15

In [79]:
arr.max()

23

In [80]:
arr.min()

15

In [83]:
arr1=np.arange(24 , 33).reshape(3,3)

In [84]:
arr1

array([[24, 25, 26],
       [27, 28, 29],
       [30, 31, 32]])

In [86]:
np.max(arr) , np.max(arr1)

(23, 32)

In [89]:
arr2=np.vstack((arr , arr1))

In [90]:
arr2.max()

32

In [91]:
arr2.min()

15

In [95]:
arr2.min()

15

In [96]:
print ("{0} min of the entire matrix".format(arr2.min()))


15 min of the entire matrix


In [99]:
print(format(arr2.max()))

32


In [100]:
format(arr2.max())      # by passing the max,min function as a paremeter in formate function to identifiy the max and min value in array 

'32'

In [102]:
format(arr2.min())

'15'

In [103]:
np.where(arr2)    #this function is used to identify the position of two array where both same element exist same place 

(array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

int64.........8unsigned bytes
int16.........4signed bytes

In [104]:
arr2.argmax()

17

In [105]:
format(arr2.argmax())

'17'

In [107]:
format(arr2.argmin())

'0'

In [109]:
format(arr2.argmin(axis=1))

'[0 0 0 0 0 0]'

In [110]:
arr2.argmax(axis=1)

array([2, 2, 2, 2, 2, 2], dtype=int64)

Statiscal Function
1 sum
2product , dot #basically use dot to product both array
3cumutativeSum
4Comutativeprod
5Mean
6Standard Derivation
7Variation

In [111]:
arr2.sum()

423

In [112]:
arr2.cumsum()

array([ 15,  31,  48,  66,  85, 105, 126, 148, 171, 195, 220, 246, 273,
       301, 330, 360, 391, 423], dtype=int32)

In [113]:
arr2.prod()

-823132160

In [114]:
arr2.cumprod()

array([         15,         240,        4080,       73440,     1395360,
          27907200,   586051200,     8224512,   189163776,   244963328,
        1829115904,   312373248,  -155856896,   -69025792, -2001747968,
          77103104, -1904771072,  -823132160], dtype=int32)

In [115]:
arr2.mean()

23.5

In [117]:
arr2.var()

26.916666666666668

In [118]:
arr2.std()

5.188127472091127

LOgical Operation.
.all show true when whole array fullfill the given condition
.any show true  if only one element in array fullfill the given condition 

In [120]:
arr=np.arange(15,45)

In [121]:
arr

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [124]:
name=(arr >20)
name.any()

True

In [126]:
name=(arr >14)
name.all()

True

In [138]:
names=np.array(['Nida','Nida','Nimra','Bushra','Ammara','Nida','Nida' , 'Ali'])

In [139]:
(names=='Nida').any()

True

In [140]:
mask=(names=='Nida')

In [141]:
data=np.random.random(7)

In [142]:
data

array([0.01345669, 0.5531551 , 0.90828066, 0.47451706, 0.20950987,
       0.64017486, 0.64725845])

In [143]:
data[mask]*10

IndexError: boolean index did not match indexed array along dimension 0; dimension is 7 but corresponding boolean dimension is 8

In [144]:
names.transpose()

array(['Nida', 'Nida', 'Nimra', 'Bushra', 'Ammara', 'Nida', 'Nida', 'Ali'],
      dtype='<U6')

In [147]:
bol=names.reshape(2,4)

In [155]:
bol.transpose()

array([['Nida', 'Ammara'],
       ['Nida', 'Nida'],
       ['Nimra', 'Nida'],
       ['Bushra', 'Ali']], dtype='<U6')

In [11]:
name=np.array(['NIMRA' ,'AYESHA' , 'ALI' , 'UMER' , 'NOOR'])

In [26]:
data=np.array(np.random.rand(5,7)*10,dtype=np.int32)                           #row and column pass as a arguments 

In [27]:
data

array([[7, 1, 5, 6, 3, 0, 7],
       [0, 2, 7, 7, 1, 4, 5],
       [0, 2, 8, 2, 7, 5, 3],
       [6, 8, 7, 8, 4, 7, 0],
       [3, 8, 8, 8, 5, 3, 3]])

In [39]:
data

array([[7, 1, 5, 6, 3, 0, 7],
       [0, 2, 7, 7, 1, 4, 5],
       [0, 2, 8, 2, 7, 5, 3],
       [6, 8, 7, 8, 4, 7, 0],
       [3, 8, 8, 8, 5, 3, 3]])

In [42]:
data[ :,[2,3,4]]     #Fancing basically use to slice the whole array into parts 

array([[5, 6, 3],
       [7, 7, 1],
       [8, 2, 7],
       [7, 8, 4],
       [8, 8, 5]])

In [35]:
datas=data[name=='ALI']

In [36]:
datas.astype(np.bool)

array([[False,  True,  True,  True,  True,  True,  True]])

# REMINDER , WHOLE PART 
# SQUARE ,EXP 

In [44]:
data=np.random.rand(20)

In [45]:
data

array([0.68288134, 0.80288137, 0.01653668, 0.21980444, 0.27520341,
       0.50553554, 0.72744443, 0.94660469, 0.34599349, 0.29841403,
       0.25597702, 0.61735969, 0.23077461, 0.58511159, 0.22874446,
       0.98562666, 0.57547589, 0.12409872, 0.99425771, 0.4038894 ])

In [46]:
np.sqrt(data)   # square root=data **0.5

array([0.82636635, 0.89603648, 0.12859503, 0.46883306, 0.52459833,
       0.71101023, 0.85290353, 0.97293612, 0.58821211, 0.54627285,
       0.50594172, 0.7857224 , 0.48039006, 0.76492587, 0.47827237,
       0.99278732, 0.75860127, 0.35227649, 0.99712472, 0.63552293])

In [52]:
reminder , whole_part=np.modf(data)  #modf function seperate the fractional and integer part as a sperate arrays

In [49]:
reminder

array([0.68288134, 0.80288137, 0.01653668, 0.21980444, 0.27520341,
       0.50553554, 0.72744443, 0.94660469, 0.34599349, 0.29841403,
       0.25597702, 0.61735969, 0.23077461, 0.58511159, 0.22874446,
       0.98562666, 0.57547589, 0.12409872, 0.99425771, 0.4038894 ])

In [53]:
whole_part

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [54]:
np.median(data)

0.4547124710451058

In [61]:
datas=np.square(data)  # square=data**2

In [62]:
datas

array([4.66326927e-01, 6.44618495e-01, 2.73461820e-04, 4.83139904e-02,
       7.57369181e-02, 2.55566186e-01, 5.29175401e-01, 8.96060435e-01,
       1.19711493e-01, 8.90509331e-02, 6.55242369e-02, 3.81132991e-01,
       5.32569185e-02, 3.42355572e-01, 5.23240274e-02, 9.71459911e-01,
       3.31172494e-01, 1.54004934e-02, 9.88548394e-01, 1.63126646e-01])

In [63]:
np.exp(datas)   #exponents

array([1.59412808, 1.90526002, 1.0002735 , 1.04950014, 1.07867876,
       1.29119247, 1.69753195, 2.44993241, 1.12717161, 1.09313633,
       1.06771862, 1.46394228, 1.05470058, 1.40826095, 1.05371712,
       2.64179844, 1.39259999, 1.01551969, 2.68733069, 1.17718577])

In [64]:
np.log(datas)   #Natural log e

array([-0.76286833, -0.43909662, -8.20434854, -3.0300341 , -2.58048955,
       -1.36427386, -0.63643533, -0.10974742, -2.12267066, -2.41854679,
       -2.72533518, -0.96460691, -2.93262756, -1.0719054 , -2.9502996 ,
       -0.02895528, -1.10511591, -4.17335573, -0.01151768, -1.81322841])

In [65]:
np.log2(datas)     # log base 2

array([ -1.10058636,  -0.63348251, -11.83637296,  -4.37141518,
        -3.72285947,  -1.96823113,  -0.9181821 ,  -0.15833206,
        -3.06236643,  -3.48922546,  -3.93182754,  -1.3916336 ,
        -4.23088724,  -1.5464326 ,  -4.2563826 ,  -0.04177363,
        -1.59434524,  -6.02087961,  -0.0166165 ,  -2.61593563])

In [66]:
np.log10(datas)   #log base 10

array([-0.33130951, -0.19069724, -3.5631033 , -1.31592709, -1.12069237,
       -0.59249661, -0.27640035, -0.0476627 , -0.92186415, -1.05036153,
       -1.18359803, -0.41892346, -1.27362397, -0.4655226 , -1.28129884,
       -0.01257512, -0.47994574, -1.81246536, -0.00500207, -0.78747509])

In [70]:
a=np.log(1+34)(datas)
a.astype(np.int)

TypeError: 'numpy.float64' object is not callable

In [12]:
survey_responses = ['Ceballos', 'Kerrigan', 'Ceballos', 'Ceballos', 'Ceballos','Kerrigan',
                    'Kerrigan', 'Ceballos', 'Ceballos', 'Ceballos', 'Kerrigan', 'Kerrigan',
                    'Ceballos', 'Ceballos', 'Kerrigan', 'Kerrigan','Ceballos', 'Ceballos', 
                    'Kerrigan', 'Kerrigan', 'Kerrigan', 'Kerrigan', 'Kerrigan', 'Kerrigan', 
                    'Ceballos', 'Ceballos', 'Ceballos', 'Ceballos', 'Ceballos', 'Ceballos',
                    'Kerrigan', 'Kerrigan', 'Ceballos', 'Ceballos', 'Ceballos', 'Kerrigan',
                    'Kerrigan', 'Ceballos', 'Ceballos', 'Kerrigan', 'Kerrigan', 'Ceballos', 
                    'Ceballos', 'Kerrigan', 'Kerrigan', 'Kerrigan', 'Kerrigan', 'Kerrigan',
                    'Kerrigan', 'Ceballos','Kerrigan', 'Kerrigan', 'Ceballos', 'Ceballos', 
                    'Ceballos', 'Kerrigan', 'Kerrigan', 'Ceballos', 'Ceballos', 'Kerrigan', 
                    'Kerrigan', 'Ceballos', 'Ceballos', 'Kerrigan', 'Kerrigan', 'Kerrigan', 
                    'Kerrigan', 'Kerrigan', 'Kerrigan', 'Ceballos']

a=np.array(survey_responses)
uniques, counts=np.unique(a , return_counts=True)
dict(zip(uniques, counts))

{'Ceballos': 33, 'Kerrigan': 37}